### PR TITLE
Adds CacheHammer. DESTROYER OF CACHES. Also makes redirects plugin agnostic.

### PR DESCRIPTION
**Pull request by rtibbles**
Note, this also merges in latest master. Hopefully this won't mess up your PR :D

### CODE REVIEW

**Comment by jtamiace** [comment]
keep-calm-and-cache-hammer

**Comment by rtibbles** [comment]
Feel free to merge to your branch so I can review and merge your PR :)

**Comment by jtamiace** [comment]
Logging out is still redirecting me to Explore

**Comment by rtibbles** [comment]
Yeah, logout will now redirect to base learn, which automatically forwards to explore.

**Pull request merged**
